language: java
before_install:
  - yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y texlive-latex-base texlive-latex-recommended texlive-latex-extra tex-gyre texlive-fonts-recommended texlive-xetex latexmk ant ant-optional
  - wget http://mirrors.ctan.org/install/macros/latex/contrib/hardwrap.tds.zip
  - sudo unzip hardwrap.tds.zip -d /usr/share/texmf
  - wget http://mirrors.ctan.org/install/macros/latex/contrib/xpatch.tds.zip
  - sudo unzip xpatch.tds.zip -d /usr/share/texmf
  - sudo texhash

# command to run tests, e.g. python setup.py test
script:
  - cd tests
  - ant
