language: java
before_install:
- yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get update -qq
- sudo apt-get install --no-install-recommends poppler-utils findutils unzip bc ant
  ant-optional libsaxonb-java texlive-binaries texlive-latex-base texlive-latex-recommended
  texlive-latex-extra tex-gyre texlive-fonts-recommended texlive-xetex latexmk pdftk
- #wget http://mirrors.ctan.org/install/macros/latex/contrib/hardwrap.tds.zip
- wget http://www.vrac.iastate.edu/~godbyk/files/hardwrap.tds.zip
- sudo unzip hardwrap.tds.zip -d /usr/share/texmf
- #wget http://mirrors.ctan.org/install/macros/latex/contrib/xpatch.tds.zip
- wget http://www.vrac.iastate.edu/files/xpatch.tds.zip
- sudo unzip xpatch.tds.zip -d /usr/share/texmf
- sudo texhash
- wget http://ftp.debian.org/debian/pool/main/l/latexmk/latexmk_4.39-1_all.deb
- sudo dpkg -i latexmk_4.39-1_all.deb
before_script:
- cd tests
- ant clean-and-run-tests > /dev/null
script:
- ./analyze-results.sh
after_script:
- ./tests/update-gh-pages.sh
env:
  global:
    secure: kuotiRvd02lHJbL3FoDKefzl/ZQnpB8cB/fl3YuKt6mA8KQr9vfX8gf+O6MYPVeCJ/uKAfXrigM8P4oJdmKhd5BTQrFRMER5XO/D+SK8fE6O1ct66efVhTsJzLvNeKT8WacCZcLvwHfAKySdlMidAhqmUfLicV+7hYyz4UX4ZD4=
